### ISSUE TITLE
Reference error when referencing parameter array

### ISSUE THREAD

**Issue by jloosli** [wework/speccy#149]
I'm trying to reference an array of parameter objects and I get a reference error when I run it through the linter.

## Detailed description

In my main openapi.yaml file, I have a path that is defined as follows:

```yaml
  /datasets/{datasets}/parts:
    get:
      tags:
      - Datasets
      operationId: datasets.parts
      summary: Get Dataset Parts
      description: Get parts for a given group of datasets.
      parameters:
        $ref: parameters/parts.yaml
      responses:
        '200':
          description: Parts Response
          content:
            application/json:
              schema:
                $ref: schemas/parts.index.json
        '401':
          $ref: '#/components/responses/UnauthorizedError'
```

parameters/parts.yaml looks like the following:
```yaml
- in: path
  name: datasets
  description: One or more dataset numbers, separated by commas.
  required: true
  schema:
    type: array
    items:
      type: integer
  explode: true
- in: query
  name: filters
  description: One or more query objects.
  required: false
  schema:
    type: array
    items:
      $ref: ../schemas/filter.json
- in: query
  name: partnumber
  required: false
  description: One or more comma separated part numbers. API will return any part numbers that match the strings.
  examples:
    single:
      value: ABC123
    multiple:
      value: ABC123,ABC1234,DEF456
  schema:
    type: array
    items:
      type: string
- in: query
  name: partnumber_vendor
  required: false
  description: One or more comma separated part numbers. API will return any part numbers that match the strings.
  examples:
    single:
      value: ABC123
    multiple:
      value: ABC123,ABC1234,DEF456
  schema:
    type: array
    items:
      type: string
```

When I run the linter, I get the following error:

```bash
Expected object or boolean as schema, got array
ReferenceError: err is not defined
    at /media/jloosli/storage/projects/partners/node_modules/oas-resolver/index.js:215:26
ReferenceError: err is not defined
    at /media/jloosli/storage/projects/partners/node_modules/oas-resolver/index.js:215:26
err is not defined
```

If I keep that same definition inline, then I don't have any errors.

## Context

When displaying my API with Redoc, it handles the parameters correctly. I can keep this inline, but I'd like to separate out components a little more since my openapi.yaml file is getting quite large. It seems like this would be valid, but I'm not 100% sure.

## Your environment

* Ubuntu 18.04
* Node 10.9.0

API isn't live yet, so no external links right now.
