### ISSUE TITLE
Question: add a lint rule to avoid boolean keys in parameters

### ISSUE THREAD

**Issue by dlouzan** [wework/speccy#283]
The YAML 1.1 spec allows to use booleans as keys of maps and performs auto-conversion, which most of the time is *not* what you want. The YAML 1.2 spec actually changes this and reduces the number of strings that can be interpreted as booleans.

I have just encountered this with one of our specs, using a construct like this:

```yaml
    Coord:
      description: A 3D coordinate
      type: object
      required:
        - x
        - y
      properties:
        system:
          description: The coordinate system
          type: string
        x:
          description: The X coordinate
          type: number
        y:
          description: The Y coordinate
          type: number
        z:
          description: The Z coordinate
          type: number
        accuracy:
          description: The accuracy of the coordinate
          type: number
```

It happened because we are performing some processing using go-yaml and they implement YAML spec 1.1:\
https://github.com/go-yaml/yaml/issues/214

The `y` parameter in the previous sample is actually interpreted by go-yaml as a `true` value, instead of the string `"y"`.

Although speccy itself properly handles this case, I think it would make sense to warn users that they are using an error-prone construct.
