### ISSUE TITLE
nullable not recognized when checking default value that is `null`

### ISSUE THREAD

**Issue by m-mohr** [wework/speccy#286]
## Detailed description

There seems to be a bug with Schema validation where nullable is set and the default value is null.

I've got a schema, which I think is completely valid:
```
    budget:
      type: number
      nullable: true
      default: null
      example: 100
```

But I get the following error:

```
#/components/schemas/budget
expected 'number' to be 'object'
```

This probably happens because null in JS is of type object and for some reason it doesn't recognize that nullable is set to true.

## Context

It rejects a valid schema and therefore should be fixed.

## Your environment

Speccy version: 0.9.0
OS: Windows 10
Node version: 11.0.0
Link to the full OpenAPI document: https://open-eo.github.io/openeo-api/v/0.4.0/openapi.json
