### ISSUE TITLE
Pattern matching on object keys incorrectly matching

### ISSUE THREAD

**Issue by colleenhardie-wf** [wework/speccy#327]
_**Edit**_: Perhaps what I'm looking for in this situation is `pathItem` and not `paths`?  If so, is there any corresponding way to refer to a model name within a schemas object?

## Detailed description

**Question/Potential bug**: I am making use of the new pattern-matching-on-object-keys feature introduced in [v0.8.7](https://github.com/wework/speccy/releases/tag/v0.8.7).  Having struggled to get my own regexes working, I've instead used the example rule provided with [the feature PR](https://github.com/wework/speccy/pull/239) as a starting point:
```
  - name: path-item-lowercased-hyphens
    object: paths
    enabled: true
    description: path items must be lowercase and separated with hyphens
    pattern:
      property: "$key"
      split: "/"
      value: "^{[^}]*}$|^([a-z-\/]*)$"
```

Using this (specified as a custom rule), the following path passes (as expected):
```
paths:
  /things:
  ...
```
Unfortunately, so does this:
```
paths:
  /Thi___***ngs:
  ...
```
If I update the value of the pattern to `"^things$"`, no match is found with the original path (but should be).

## Context

This is a potential issue with a pre-existing feature.  When functioning as expected, it prevents the need for hand-rolled validation checks.  This is advantageous for everyone.

## Possible implementation

As yet, I don't see the correct fix, or whether this is simply a PEBKAC.

## Your environment

* speccy version: 0.9.0
* Node Version: v10.15.3
