### ISSUE TITLE
Creating a rule to validate schema name casing.

### ISSUE THREAD

**Issue by miller79** [wework/speccy#359]
My goal is to create a rule based on the schema's name casing like if I wanted to check the below to ensure its in CamelCase:

```yaml
components:
  schemas:
    api-error:
      type: object
```

I have tried the following but it did not work as intended:

```yaml
rules:
- name: casing-rule
  object: schemas
  description: reference components should all match regex ^[a-zA-Z0-9\.\-_]+
  pattern:
    property: name
    value: ^[A-Z][a-zA-Z]*$
```

Is this feature not possible or am I missing something from the documentation.  If I am missing something from the documentation, I would suggest adding this to the documentation for any one else who needs to do this as well.
