### ISSUE TITLE
Escape colon

### ISSUE THREAD

**Issue by VonSerpe** [wework/speccy#371]
## Detailed description

When I create an example with a value that contains a colon like this:
```yaml
range:
  summary: Bla bla bla
  value:
    range: '4:23'
```
`speccy resolve` command converts the range value string in a value without quote:
```yaml
range:
  summary: Bla bla bla
  value:
    range: 4:23
```
and in SwaggerHub editor I see this:
```json
{
  "range": 263
}
```

## Possible implementation

When quotes are used to define the value of a variable, `speccy resolve` command can consider the quotes and apply them to the generated file

## Your environment

Include as many relevant details about the environment you experienced the bug in and how to reproduce it.

* Node Version: v10.16.3
* Operating system and version (e.g. Ubuntu 16.04, Windows 7): macOS High Sierra 10.13.6
