### ISSUE TITLE
resolve does not import tags

### ISSUE THREAD

**Issue by pourquoi42** [wework/speccy#435]
## Detailed description

given 2  specs A,B:

spec A contains
```
paths:
  /stuff:
    $ref: B.yaml#/paths/~1thingies
```
spec B conatins
```
tags:
  - name: ext
    description: description

paths:

  /thingies:
    get:
      tags:
          - ext

```
`speccy resolve A.yaml`
 includes the thingies path, but it does not take the tag with it's description into the merged file.

## Context

in an environment where there is one spec to be presented to users that merges several specs coming from different teams, this feature is vital in the compilation of the one and only spec

## Possible implementation

Simply add the tags in the result
